### ISSUE TITLE
vals for KeyCodes?

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#104]
@sjrd Question about efficiency here. We have:
```scala
object KeyCode {
  val backspace = 8
  val tab = 9
  // etc
```

Is there effeciency to be gained by changing to `final val`s?

I was thinking `@inline def` would be best but then they can be used in pattern matching.

**Comment by sjrd** [comment]
`final val` is best, indeed.

**Comment by japgolly** [comment]
Cool, I'll make another PR for this after we finish with #103.

**Comment by japgolly** [comment]
Lumped into #105
