### ISSUE TITLE
xhr.responseURL for redirects

### ISSUE THREAD

**Issue by bblfish** [scala-js/scala-js-dom#111]
In order to be able to find out if a request was redirected to another URL one needs to use the `responseURL` method on `XMLHTTPRequest`s which I found defined in the [whatwg xhr spec](https://xhr.spec.whatwg.org/#the-responseurl-attribute).

Currently [the code I had to write](https://github.com/read-write-web/rww-scala-js/blob/a78866dd082813bcca92f71b785fa839d50dbbb4/src/main/scala/rww/cache/WebStore.scala#L32) which works, but is not nice, looks like this:

``` scala
  val redirectURL = xhr.asInstanceOf[js.Dynamic].responseURL.asInstanceOf[String]
```

You can test it in the browser by compiling and [running the html](https://github.com/read-write-web/rww-scala-js/blob/a78866dd082813bcca92f71b785fa839d50dbbb4/html/foaf.html)

It may be useful to have a static implementation - though I think it should be done in a way to take account of many browsers returning an undefined value I suppose.

**Comment by bblfish** [comment]
As expected the simple version did not work with Safari or older browsers. Using UndefOr helped [as shown here](https://github.com/read-write-web/rww-scala-js/blob/5e7df29125b479234f5ecd697b2a61dd5b71d416/src/main/scala/rww/cache/WebStore.scala)

**Comment by sjrd** [comment]
PR welcome.

**Comment by bblfish** [comment]
Taking time for PR, as I need to get much more familiar with the ecosystem, before I can feel confident I am doing the right thing.
