### ISSUE TITLE
ScrollTop value on HTMLTextAreaElement not set

### ISSUE THREAD

**Issue by mathieuleclaire** [scala-js/scala-js-dom#125]
Hi,
when I (try to) change the value of the scrollTop attribute on a HTMLTextAreaElement, the value is not set.
Mathieu

```scala 
import scalatags.JsDom.{ tags ⇒ tags }
import scalatags.JsDom.all._

val tARender: HTMLTextAreaElement = tags.textarea(`class` := "form-control", rows := 20).render
tARender.scrollTop = 999.0
println("TOP " + tARender.scrollTop)
```

**Comment by mseddon** [comment]
A lot of behaviours in the DOM require the element to be attached to the document to take effect.  I believe you're running into an issue along these lines.  See https://jsfiddle.net/fz5LnLng/1/

Try adding it to the document somewhere before you set scrollTop.

**Comment by mseddon** [comment]
@sjrd vote to close this since it's not an issue with `scala-js-dom`, and has been idle for 6 months.

**Comment by sjrd** [comment]
Indeed.
