### ISSUE TITLE
Constructors don't work for DOM elements

### ISSUE THREAD

**Issue by ghik** [scala-js/scala-js-dom#127]
I don't see a reason why DOM elements like `HTMLElement` are represented by classes and not traits or abstract classes.

Currently the compiler does not protect us from trying to create HTML elements with plain constructor but it won't work in runtime.

**Comment by sjrd** [comment]
Those for which creation at runtime is not permitted by the spec should indeed be abstract classes.

**Comment by mseddon** [comment]
Any reason to use `abstract class` over `trait`? We tend to use `trait` in things like AudioAPI, WebGL, etc., so it would be more consistent if possible to use trait, I'd say.

**Comment by sjrd** [comment]
Yes, you can do `x.isInstanceOf[dom.HTMLElement]` if `HTMLElement` is a class. It translates to `x instanceof HTMLElement` in JS. You can't do that if it's a trait.

**Comment by mseddon** [comment]
Gotcha, okay, I'll go with that, then.
