### ISSUE TITLE
TimeRanges start and stop have wrong type (Int instead of Double)

### ISSUE THREAD

**Issue by Sciss** [scala-js/scala-js-dom#137]
Here: 

- https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/raw/lib.scala#L5081
- https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/raw/lib.scala#L5088

I am getting runtime errors:

> Uncaught scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: 67.57 is not an instance of java.lang.Integer

I think these values are measured in seconds that have been buffered.

**Comment by sjrd** [comment]
PR welcome :-)

**Comment by Sciss** [comment]
Yes, sorry, next time! Thanks for your work.

**Comment by mseddon** [comment]
Oh, sorry, didn't mean to steal that from you- I tend to fix these up as I find them :) new contributors always welcome!
