### ISSUE TITLE
PerformanceTiming claims to return Int but they overflow

### ISSUE THREAD

**Issue by behaghel** [scala-js/scala-js-dom#139]
I was trying to use it but I systematically get the following error when I access any of its values: `XXXXX is not an instance of java.lang.Integer` in the browser. Taking the js.Dynamic route works fine.

Fails:
```scala
    val window = dom.document.defaultView
    val perf = window.performance.timing
    PageLoad(perf.loadEventStart - perf.navigationStart)
```

Works:
```scala
    val window = DOMGlobalScope.window
    val perf = window.performance.timing
    PageLoad(perf.loadEventStart.asInstanceOf[Double] - perf.navigationStart.asInstanceOf[Double])
```

**Comment by sjrd** [comment]
I guess it should return `Double` ...
Thanks for the report.
