### ISSUE TITLE
make SVG html element

### ISSUE THREAD

**Issue by antonkulaga** [scala-js/scala-js-dom#159]
I wonder why 

``` html
<svg>
</svg>
```

does not inherit HTMLElement?

**Comment by lihaoyi** [comment]
Because it isn't one

<img width="720" alt="screenshot 2015-10-12 11 48 21" src="https://cloud.githubusercontent.com/assets/934140/10435819/32a0d3fc-70d7-11e5-893d-e2b6911762a8.png">

As to "why", that's beyond my pay grade =P

**Comment by sjrd** [comment]
Exactly what I was going to say. Also documented here: https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement

**Comment by mseddon** [comment]
We have `SVGElement`, which extends Element.  Techically I also think that `HTMLDocument` and `SVGDocument's` createElements should return the more specific type (`HTMLElement`/`SVGElement`), but currently they do not (they punt and return `Element` iirc.

Is there any reason we shouldn't do some path dependent magic here?

**Comment by sjrd** [comment]
@mseddon I agree we should improve the result type of `createElement` and, if possible, other such methods, but that is another issue.

**Comment by antonkulaga** [comment]
SVGElement has a bunch of fields that are the same as HTMLElement, in particular
```
  var onmousemove: js.Function1[MouseEvent, _] = js.native
  var onmouseout: js.Function1[MouseEvent, _] = js.native
  var ondblclick: js.Function1[MouseEvent, _] = js.native
  var onfocusout: js.Function1[FocusEvent, _] = js.native
  var onfocusin: js.Function1[FocusEvent, _] = js.native
```
maybe we can hve a trait with them from which both HTMLElement and SVGElement will extend? In such case I will be able to operate with HTMLElements and SVGElements in a same manner when I only care about event subscriptions

**Comment by matanster** [comment]
I can see this already addressed in https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/svg.scala
