### ISSUE TITLE
Move to scala-js 0.6.5

### ISSUE THREAD

**Issue by mseddon** [scala-js/scala-js-dom#163]
0.6.5 adds `|`, which will enable tightening up a lot of the signatures, so I'd vote to move to it if possible.
On the other hand, if we're intentionally staying with 0.6.2 for backwards compatibility, then perhaps we shouldn't just yet.  Thoughts?

**Comment by sjrd** [comment]
Yes the bump to 0.9.0-SNAPSHOT was meant to support upgrading to Scala.js 0.6.5.
