### ISSUE TITLE
generateKey API not flexible enough

### ISSUE THREAD

**Issue by bblfish** [scala-js/scala-js-dom#166]
The crypto api mapping is not general enough. The definition I see is:
 ```scala
def generateKey(algorithm: String, extractable: Boolean,
      keyUsages: js.Array[String]): Promise[js.Any] = js.native
```
the algorithm seems to also potentially be an object according to [this blog post](http://blog.engelke.com/tag/webcrypto/) where the example code is 
```JavaScript
window.crypto.subtle.generateKey(
            {
                name: "RSASSA-PKCS1-v1_5",
                modulusLength: 2048,
                publicExponent: new Uint8Array([1, 0, 1]),
                hash: {name: "SHA-256"}
            },
            true,   // Must extract private key to create PEM files later
            ["sign", "verify"]).
```

It's actually not that easy to read these JS specs, and  [WebCrypto API](http://www.w3.org/TR/WebCryptoAPI/#subtlecrypto-interface) is not exceptions. Still the definition there is 

```JavaScript
Promise<any> generateKey(AlgorithmIdentifier algorithm,
                          boolean extractable,
                          sequence<KeyUsage> keyUsages );
```

**Comment by bblfish** [comment]
One thing that one could do is make algorithms typesafe, as for example I have been trying with the [Fetch API](https://github.com/scala-js/scala-js-dom/issues/167).

Here things may be a bit different. I was thinking in this case algorithms for example could not be sealed traits, but it seems according to [this stackoverflow article](http://stackoverflow.com/questions/28429928/web-cryptography-api-howto-discover-supported-algorithms) that it is not actually possible to discover supported algorithms in the browser.  Still I suppose developers could integrate libraries that support them and ship those with the code....

**Comment by mseddon** [comment]
When I initially PR'd the web crypto api, @sjrd suggested that we could use path dependent types to actually provide accurate types for all the promises, so I think it might be worth mapping out the various routes through the api.  I believe we can produce accurate typing for the known algorithms, with a fallback to Promise[Any] when the user uses something we've not seen before.

**Comment by bblfish** [comment]
That sounds like a good idea. The above changes get me far enough to continue programming my implementation of [http-signatures](https://tools.ietf.org/html/draft-cavage-http-signatures-05)
