### ISSUE TITLE
Enforce `Event => Unit` Event handlers

### ISSUE THREAD

**Issue by elacin** [scala-js/scala-js-dom#170]
Wouldn't it be better if we enforced that event handlers return `Unit`?
That is change this:
```scala 
var onmousedown: js.Function1[MouseEvent, _] = js.native
```
to this:
```scala 
var onmousedown: js.Function1[MouseEvent, Unit] = js.native
```

If you agree i can for sure throw up a PR with the necessary changes

**Comment by lihaoyi** [comment]
I don't remember why I did this initially, but IIRC there was some odd interaction which made type-inference sad if i made it have an explicit `Unit`. @sjrd do you remember?

**Comment by sjrd** [comment]
It would be worse. The `Any/_` result type is better. It allows to use a lambda that returns anything, not only lambdas that return `Unit`. This is similar to how `foreach` in the Scala collections accepts functions that return anything.
