### ISSUE TITLE
removeEventListener should take `js.Function1[_ <: Event, _]`

### ISSUE THREAD

**Issue by mpartel** [scala-js/scala-js-dom#175]
`EventTarget#addEventListener` takes a `js.Function1[T, _]` for any `T <: Event` but `EventTarget#removeEventListener` only accepts a `js.Function1[Event, _]`. It should probably also take a `js.Function1[T, _]`.

**Comment by mseddon** [comment]
This has already been addressed in https://github.com/scala-js/scala-js-dom/commit/3c689a74ed7b7cc669d236ecedf53b9efc95329c

It should be released already, in `0.8.2`.

**Comment by mpartel** [comment]
Ah, sorry, I thought my deps were more up to date than they actually were.

**Comment by mseddon** [comment]
No problem :)
