### ISSUE TITLE
We're leaking experimental APIs

### ISSUE THREAD

**Issue by mseddon** [scala-js/scala-js-dom#180]
It appears the WebAudio api accidentally introduced a `MediaStream` trait (stubbed) into `scala.js.dom.raw` [here](https://github.com/scala-js/scala-js-dom/blob/e5b10a70771ae65bf666c55a6b21c626da2adbd5/src/main/scala/org/scalajs/dom/raw/lib.scala#L5508).  This type is also forwarded in `dom`.

As you can see [though](http://caniuse.com/#feat=stream), it's not compatible enough to meet the criteria of being outside of `experimental`.  But sadly, we've released it in `0.8.1` and `0.8.2`.

There may be others, and I will investigate.

@sjrd @lihaoyi I wonder since the next release will be `0.9.0` if we do some slightly breaking reorganization to fix up anything that slipped out? Hopefully it won't impact too many people.  

https://github.com/scala-js/scala-js-dom/pull/179 fleshes out the ~~`MediaStream`~~ class (because it's needed for WebRTC), but I've been afraid to move it into experimental without checking with you guys that this breaking change is acceptable.

**Comment by sjrd** [comment]
Sure, we can break things.

You can also add a deprecated forwarder in the original location.

**Comment by mseddon** [comment]
Ah, that's good- I wasn't sure if it was possible to annotate `types`.  That makes this kind of reorg is much less worrying.

**Comment by mseddon** [comment]
`ServiceWorker`, `ServiceWorkerRegistration`, `ServiceWorkerContainer` and `NavigatorID`, all want to live in `experimental.servieworker`.

**Comment by mseddon** [comment]
`Promise` is sort of annoying- http://caniuse.com/#feat=promises since they're not present in IE11.  They are in Edge, but that unfortunately doesn't mean anything to windows 7 and windows 8 users.

**Comment by sjrd** [comment]
`Promise` needs to go to core anyway, because it's specified in ES6 itself.

**Comment by mseddon** [comment]
`EventSource` is not supported in IE or Edge.

**Comment by mseddon** [comment]
That's everything I found in `lib.scala`.  It appears `WebAudio.scala` in general should live in `experimental`, because it is not supported under IE.

**Comment by mseddon** [comment]
IndexDB is an interesting one.  IE and Edge don't support some operations, and Safari's implementation is just broken.  Technically it's "present" though.

**Comment by kapunga** [comment]
Is this still an issue?  If it is, I'd be happy to go clean up what is left.

**Comment by mseddon** [comment]
@kapunga Thanks! The obvious one remaining I think is the WebAudio api, but if `EventSource` is not heavily referenced it would also be fairly trivial to migrate.

**Comment by kapunga** [comment]
Okay, I'm starting work on this.  :-)

**Comment by kapunga** [comment]
@mseddon Actually, nevermind, I think the MediaStream stuff is all covered in PR #203?  IT looks like that's it for this issue, so I guess when it's fix, it should be good.

**Comment by mseddon** [comment]
@kapunga the reasoning behind WebAudio in general being experimental for now is that it is not supported on IE11.  Currently IE11 has considerable market share (in that, it would be unwise to build a site that does not target it today), and the purpose of the `experimental` package is to flag libraries that fall into these edge cases.  I would definitely say that at least until Edge absorbs these users, we don't want to trick people into thinking it is 'common'.

**Comment by armanbilge** [comment]
Another one to tuck under the rug I think 😅
