### ISSUE TITLE
Support for SharedWorker

### ISSUE THREAD

**Issue by danielwegener** [scala-js/scala-js-dom#186]
There is already an interface for `Worker` and `AbstractWorker`. It would be nice if we could support the [`SharedWorker`](https://developer.mozilla.org/de/docs/Web/API/SharedWorker) too!

**Comment by mseddon** [comment]
:+1: definitely.  Actually if we could migrate the existing service workers code into `org.scalajs.dom.experimental.serviceworker` during this, it would help us address #180, as well. :)

**Comment by kapunga** [comment]
Is service worker migration happening on this ticket?  I have to extend some parts of the ServiceWorker API for #184 and was considering attempting to move all of them over instead.  Would like to avoid conflicts though.

**Comment by danielwegener** [comment]
Yeah I already moved around some bits and pieces in #187 . It also adds alot of ServiceWorker related api (most of the Context parts). Although the packaging is not yet finally discussed (feel free to jump in).
