### ISSUE TITLE
Helpful methods for HTMLCollection

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#194]
Would you be interested in adding these useful functions the library?
They make `element.children` act a bit more Scala-idiomatically.

```scala
@inline implicit class PatchHTMLCollection(private val c: raw.HTMLCollection) extends AnyVal {
  def nonEmpty: Boolean =
    c.length > 0

  def isEmpty: Boolean =
    !nonEmpty

  def headOption: Option[Element] =
    if (nonEmpty) Some(head) else None

  def lastOption: Option[Element] =
    if (nonEmpty) Some(last) else None

  def head: Element =
    c(0)

  def last: Element =
    c(c.length - 1)

  def iterator: Iterator[Element] =
    (0 until c.length).iterator.map(c.apply)

  def deepIteratorDepthFirst: Iterator[Element] =
    iterator.flatMap(e => Iterator.single(e) ++ e.children.deepIteratorDepthFirst)

  def deepIteratorBreadthFirst: Iterator[Element] =
    iterator ++ iterator.flatMap(_.children.deepIteratorBreadthFirst)
}
```

If interested, please tell me where you'd like me to put them and how.

**Comment by lihaoyi** [comment]
Would another option be to instead of adding a bunch of individual extension methods, have an implicit conversion into a `Seq[T]`?

**Comment by sjrd** [comment]
I agree with @lihaoyi. That's what we did for `js.Array`.

**Comment by japgolly** [comment]
Ah, no worries.

**Comment by bbarker** [comment]
Where does said implicit conversion exist (or does it)? Or was the suggestion that we should use our own implicit conversion in each project that needs it?

**Comment by mseddon** [comment]
@bbarker the implicits should be imported into scope from `org.scalajs.dom.ext`.

**Comment by dportabella** [comment]
Example on how to use it:
```
import org.scalajs.dom.ext._
document.body.children.map(_.textContent)
```
