### ISSUE TITLE
def decrypt(algorithm: KeyAlgorithmIdentifier, ...)

### ISSUE THREAD

**Issue by bblfish** [scala-js/scala-js-dom#196]
@povder started a [discussion on an already committed PR](https://github.com/bblfish/scala-js-dom/commit/d0800da8fb13d14817d556dbce000df9f24e5211#diff-18d86255e344ee8787bb13b29aca28beR167) about the method `SubtleCrypto.decrypt(algorithm: KeyAlgorithmIdentifier, key: CryptoKey, ...)`. 

In summary either:
1. `algorithm` should be extended to type `AlgorithmIdentifier` 
2. ` AesGcmParams` should extend `KeyAlgorithmIdentifier`

**Comment by bblfish** [comment]
1. may be closer to the official spec, but for a newbie like me it's a bit odd that one could decrypt something with a hash algorithm.
2. would require a cryptographer to verify the logic of what we are doing

**Comment by povder** [comment]
Please see https://github.com/scala-js/scala-js-dom/pull/190
