### ISSUE TITLE
New dom package is missing various APIs since upgrading to 0.9.x

### ISSUE THREAD

**Issue by mseddon** [scala-js/scala-js-dom#205]
In https://github.com/scala-js/scala-js-dom/commit/45053e038a4d3f3ba7f7bd699f840a0cc660bb4f, the `dom` package was converted into a regular package object that does _not_ inherit `Window` to work around issues with package objects inheriting `js.Any` (this is now officially deprecated in Scala.js).  This means that many of the elements inherited from `Window` are no longer available directly in the `dom` package.  Apologies for this necessary breaking change.  Further details can be found in https://github.com/scala-js/scala-js-dom/issues/121.

_In general- if you run into a missing api from `dom` after upgrading to `0.9.x`, your best bet is to look in `dom.window` for it._

This issue tracks items that were removed from the root `dom` package in `0.9.0` that are reported.  If people feel strongly about including or not including these items back in the root `dom` package, you are encouraged to speak up!  Feel free to post any breakage reports and your feelings on them here.

Currently I've had reports of the following two changes causing surprise:

`dom.localStorage` is now `dom.window.localStorage`
`dom.sessionStorage` is now `dom.window.sessonStorage`.

**Comment by mseddon** [comment]
`dom.setInterval` is now `dom.window.setInterval`
`dom.setTimeout` is now `dom.window.setTimeout`
`dom.clearTimeout` is now `dom.window.clearTimeout`
`dom.setImmediate` is now `dom.window.setImmediate`

**Comment by mseddon** [comment]
This should almost certainly be published in the documentation since this confusion is still cropping up :(

**Comment by armanbilge** [comment]
Hopefully this is well enough in the past we can tuck it under the carpet 😅
