### ISSUE TITLE
Issues with RTCDataChannel API

### ISSUE THREAD

**Issue by danielwegener** [scala-js/scala-js-dom#209]
Hi folks,

I just tried to migrate my data-channel playground app to current 0.9.0-SNAPSHOT using WebRTC API provided by #203 and found some small issues:

- `RTCPeerConnection.createDataChannel` is not callable, its missing its `RTCDataChannelInit` parameter
- `RTCPeerConnection.ondatachannel` does not emit an `RTCDataChannelEvent`, so one can not react on data channels requested by the peer.
- some properties on `RTCPeerConnection` are `val` but their value change over time. Wonder if it would make more sense to expose them as `def`.

**Comment by sjrd** [comment]
> some properties on RTCPeerConnection are val but their value change over time. Wonder if it would make more sense to expose them as def.

Yes, they should be `def`s in this case!
