### ISSUE TITLE
Clean up structure of experimental package.

### ISSUE THREAD

**Issue by mseddon** [scala-js/scala-js-dom#215]
The experimental package was perhaps a bit too experimental when it started out.

`Fetch`, `Fullscreen`, `Notification`, `PointerLock`, `Stream` and `Vibration` should really live in their own sub packages in experimental, rather than loose.  This maintains consistent import usage with the larger apis and prevents pollution of the experimental package object by arbitrary specifications (e.g. currently the Fetch api).

**Comment by armanbilge** [comment]
wontfix for series/1.x for compatibility reasons, but will be fixed in series/2.x :)
