### ISSUE TITLE
Support HTMLDialogElement

### ISSUE THREAD

**Issue by halfmatthalfcat** [scala-js/scala-js-dom#223]
Support for the Dialog element is [slowly gaining support](http://caniuse.com/#feat=dialog) among browsers and is already implemented in Chrome/Opera. Add a scalajs interface per the HTMLDialogElement spec: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement

**Comment by armanbilge** [comment]
5 years later yet still less than 75% at caniuse :(

**Comment by Lasering** [comment]
[Now](https://caniuse.com/?search=dialog) is at 87.75% (with IE still being included).
