### ISSUE TITLE
KeyFrames

### ISSUE THREAD

**Issue by mathieuleclaire** [scala-js/scala-js-dom#226]
Hi,
I'd like to use CSS keyframes through scala-js-dom. I tried this: 

``` scala
val kfRule = new CSSKeyframesRule
kfRule.name = "dialogKF"
kfRule.appendRule("0%  {top: 0px;}")
kfRule.appendRule("20%  {top: 100px;}")
```

but the instanciation fails at runtime: 

``` sh
TypeError: m.CSSKeyframesRule is not a constructor
```

Should I use it in a different manner ?

**Comment by sjrd** [comment]
What would be the Javascript code that would work?

**Comment by mathieuleclaire** [comment]
I try to generate keyframe CSS stuff (like http://www.w3schools.com/cssref/css3_pr_animation-keyframes.asp), but I don't know the equivalent JS code; I just discovered it in the scala-js-dom API.

**Comment by mathieuleclaire** [comment]
The question is more: is it possible to deal with [CCS at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) with scala-js-dom (as it is possible to deal with styles) ?

**Comment by exoego** [comment]
Now [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) has working draft and is [getting partial support by browsers](https://caniuse.com/#feat=web-animation).

**Comment by armanbilge** [comment]
Unclear what the corresponding JS code is, happy to reopen with an example.
