### ISSUE TITLE
WebWorker onmessage parameter should be MessageEvent

### ISSUE THREAD

**Issue by ochrons** [scala-js/scala-js-dom#231]
Currently defined as:

`var onmessage: js.Function1[js.Any, _] = js.native`

which prevents defining a handler function like,

```
    val worker = new Worker("worker.js")
    worker.onmessage = (e: dom.MessageEvent) => { }
```

`onmessage` should be defined as:

`var onmessage: js.Function1[MessageEvent, _] = js.native`

see https://developer.mozilla.org/en-US/docs/Web/API/Worker/onmessage

**Comment by mseddon** [comment]
Yep, this looks correct.  The WebWorker draft is referential spaghetti, but it's defined in the [Web Messaging API](https://www.w3.org/TR/webmessaging/#the-messageevent-interfaces). Might be worth verifying the signature of `MessageEvent` hasn't changed while we're at it.

**Comment by exoego** [comment]
This can be closed since it is fixed in https://github.com/scala-js/scala-js-dom/pull/224
