### ISSUE TITLE
HTMLElement.adEventListener should accept also ThisFunction as callback

### ISSUE THREAD

**Issue by scalway** [scala-js/scala-js-dom#248]
currently adEventListener() accepts only `(e:Event) => Any` as callback but should  `ThisFuntion1[HTMLElement, Event, Any]`.

this paragraph shows great use case:
https://javascript.info/tutorial/bubbling-and-capturing#this-and-event-target

**Comment by sjrd** [comment]
What use case is not covered by `e.currentTarget` nor simply have a reference to the object in the lexical scope?

**Comment by armanbilge** [comment]
Happy to reconsider if anyone still wants this.
