### ISSUE TITLE
Tighten History.go() param type

### ISSUE THREAD

**Issue by danielnixon** [scala-js/scala-js-dom#254]
[History.go()](https://github.com/scala-js/scala-js-dom/blob/master/src/main/scala/org/scalajs/dom/raw/lib.scala#L5171) currently accepts a `delta: js.Any`. We can tighten this up to `delta: Int|String` if we want to continue to support IE's non-standard behavior, or even tighter to `delta: Int` if we don't.

**Comment by sjrd** [comment]
I'd say `Int`. scalajs-dom is supposed to represent the standard, unless there is a compelling reason not to.

**Comment by andersschuller** [comment]
As far as I can tell based on the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/History_API) and [this spec](https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface), this isn't the only issue with the navigation methods in `History`. The `back` and `forward` methods can currently take a single `distance` parameter, but the links above list them as being parameterless.

In a minute I'll create a pull request to fix both of these issues.
