### ISSUE TITLE
Remove/deprecate HTMLBlockElement & HTMLPhraseElement

### ISSUE THREAD

**Issue by danielnixon** [scala-js/scala-js-dom#272]
HTMLBlockElement and HTMLPhraseElement don't appear in any of the specs and I can't conjure either of them in Firefox. Searching the web suggests they're IE-specific implementation details that may or may not still exist in recent versions of IE.

**Comment by sjrd** [comment]
PR welcome.

**Comment by aappddeevv** [comment]
block should be blockquote
