### ISSUE TITLE
Source map links are wrong

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#275]
Use scala-js-dom with scalajs-bundler and you'll get a bunch of warnings about `/localhome/doeraene` not existing.

```
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file '../../../../../../../../localhome/doeraene/projects/scalajs-dom/src/main/scala/org/scalajs/dom/package.scala': Error: Can't resolve '../../../../../../../../localhome/doeraene/projects/scalajs-dom/src/main/scala/org/scalajs/dom/package.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
```

Think you need something like [this](https://github.com/japgolly/scalajs-react/blob/v1.0.0-RC1/project/Build.scala#L74-L81).

**Comment by sjrd** [comment]
Yes, we need that, indeed!

**Comment by japgolly** [comment]
Actually, I should be a good citizen. Let me create a PR now :)
