### ISSUE TITLE
Node.nodeValue should be var

### ISSUE THREAD

**Issue by ochrons** [scala-js/scala-js-dom#280]
Currently `nodeValue` is a `def` but it should be `var` to allow setting a new `nodeValue`.

From https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeValue

> The Node.nodeValue property returns or sets the value of the current node.

For `Text` node a work-around is to use the `data` property.

**Comment by exoego** [comment]
It seems that `nodeValue` supposed to [raise Exception on setting in DOM Level 2](https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-1950641247).
[In DOM Level 4, it won't](https://www.w3.org/TR/dom/#interface-node).
