### ISSUE TITLE
Document how these bindings were generated

### ISSUE THREAD

**Issue by danr** [scala-js/scala-js-dom#307]
Hi, I cannot find any information (and I skimmed through parts of the source code) how these bindings were generated. What's the procedure?

Thanks!

**Comment by sjrd** [comment]
An initial version was generated 4 years ago using https://github.com/sjrd/scala-js-ts-importer. Since then, they have been improved and maintained by hand.

Nowadays there is no procedure that can be followed to regenerate them.
