### ISSUE TITLE
Support for write of svg attribute?

### ISSUE THREAD

**Issue by doofin** [scala-js/scala-js-dom#310]
I saw that attributes for svg elements like circle can only read but not write
```scala
val circ=dom.document.createElementNS(http://www.w3.org/2000/svg, "circle").asInstanceOf[Circle]
circ.cx=5 // don't work, cx is defined as def in svg facades and is  read only
```

**Comment by sjrd** [comment]
If the specification says that it is mutable, then we should make it mutable. PR welcome.

**Comment by doofin** [comment]
The specs do not say mutability about that [https://www.w3.org/TR/SVG/shapes.html#CircleElementCXAttribute](url) ,but it seems that this is `attribute` rather than `property`, which needs to be set by `elem.setAttribute()`. So dom api is really disgusting to work with.. Do you think we should use some tricks like defining some implicit classes  which defines := symbol to make it work? Like `circ.cx:=5`

**Comment by sjrd** [comment]
If the spec says it should be set with `setAttribute()`, then you should use `setAttribute()`. Don't add implicit stuff on top of that. We can write custom Scala.js libraries on *top* of scalajs-dom for that. `scalajs-dom` should closely resemble the original DOM API.
