### ISSUE TITLE
block => blockquote

### ISSUE THREAD

**Issue by aappddeevv** [scala-js/scala-js-dom#311]
Re: #272, block should really be blockquote

Some notes:
missing html elements (some of which are equiv to Element):
* article
* aside
* b
* br
* caption
* cite
* code
* col
* colgroup
* data
* del
* details (no IE?)
* dfn
* dialog (not well supported)
* dl
* dt
* em 
* H1-6 (map to heading)

**Comment by armanbilge** [comment]
Closing without much investigation because this issue seems broad and possibly outdated. Apologies and please feel free to open another one!
