### ISSUE TITLE
Type of PermissionStatus.onChange

### ISSUE THREAD

**Issue by cornerman** [scala-js/scala-js-dom#322]
Currently `onChange` in PermissionStatus [is defined as `Function1[PermissionState, _]`](https://github.com/scala-js/scala-js-dom/blob/28336278149fdecdd3e2e73b3c317dbd23eff6b1/src/main/scala/org/scalajs/dom/experimental/permissions/package.scala#L27).

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus/onchange) does not document the type of the parameter, but in their example use it without an argument. When using it in the browser I get an Event (`Event {isTrusted: true, type: "change", target: PermissionStatus, currentTarget: PermissionStatus, eventPhase: 2, …}`), which looks like some kind of PermissionStatusEvent, which I cannot find anything about.

I guess, the type of onchange should be `Function1[dom.Event, _]`?

**Comment by sjrd** [comment]
Yes, it should be a `dom.Event`. The best reference is not MDN, it is [the specification](https://w3c.github.io/permissions/#status-of-a-permission), which says that `onchange` is an `EventHandler`.
