### ISSUE TITLE
SVGTextContentElement.getComputedTextLength(): Int should return a Double

### ISSUE THREAD

**Issue by georgeorfanidi** [scala-js/scala-js-dom#336]
https://github.com/scala-js/scala-js-dom/blob/47af225e9f3022b9deffbbbb5dd4b098dec2beca/src/main/scala/org/scalajs/dom/raw/Svg.scala#L1898

getComputedTextLength() better return Double

**Comment by sjrd** [comment]
Spec text: https://svgwg.org/svg2-draft/text.html#InterfaceSVGTextContentElement

**Comment by exoego** [comment]
This issue can be closed since it is already fixed in #341
