### ISSUE TITLE
Parsing rule is too strict for HTML color representations

### ISSUE THREAD

**Issue by mysticfall** [scala-js/scala-js-dom#34]
Currently, regular expressions used by the `Color` class is too strict and it causes an MatchError when it tries to parse such strings:
- _" #ff1234"_
- _" #1234aa "_
- _" #ffff"_
- _"rgb(123,234,452)"_
- _"rgb(123, 234, 452 )"_

It would be better if it at least allows arbitary number of spaces/tabs/line breaks between significant numbers.

**Comment by armanbilge** [comment]
@mysticfall still interested to PR this? Would be much appreciated!!

**Comment by sjrd** [comment]
`Color` is going away for 2.x in #458, so I don't think this is worth giving at this point.
