### ISSUE TITLE
Use DOMException instead of DOMError

### ISSUE THREAD

**Issue by floating-cat** [scala-js/scala-js-dom#374]
The current method signature of `FileReader.error` is 
```scala
def error: DOMError = js.native
```
But from [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/error):
> A DOMError containing the relevant error. In Chrome 48+/Firefox 58+ this property returns a DOMException because DOMError has been removed from the DOM standard.

The `DOMError` MDN page also says this DOMError was deprecated.

Also the `DOMError` and the `DOMException` APIs in scala-js-dom is not complete. The MDN `DOMException class` has three methods, but scala-js-dom API only has two, the deprecated message for `DOMException.code` is not incorrect now.

**Comment by sjrd** [comment]
Thank you for the report. PR welcome :)

**Comment by floating-cat** [comment]
I will send a PR later :)
