### ISSUE TITLE
Upgrade TypedArray support in WebGL etc. to use Scala Array once we move to 0.5.2 or above

### ISSUE THREAD

**Issue by mseddon** [scala-js/scala-js-dom#39]
Currently scala-js-dom is compiled against scala-js 0.5.

Once we move to 0.5.2+ we can rip out my increasingly silly TypedArray interfaces and change all the signatures.

**Comment by sjrd** [comment]
This was done in 30bde3ea4de0d2b8f690469a413e195a813c33a8
