### ISSUE TITLE
DD & DT elements

### ISSUE THREAD

**Issue by damercier** [scala-js/scala-js-dom#400]
Hello, 

Why were the DD and DT considered non-standard and removed in 1.0.0 version? 

There are valid HTML5 elements. 
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd and https://www.w3.org/TR/html52/grouping-content.html#the-dt-element 

Can we re-introduce those missing elements in the next release?

_Originally posted by @damercier in https://github.com/scala-js/scala-js-dom/pull/360/review_comment/create_

**Comment by sjrd** [comment]
The HTML elements are standard, but their programmatic API are in both cases `HTMLElement`, not a more specific `HTMLDDElement`/`HTMLDTElement` (which do not exist). This is written under "DOM Interface" in the links that you point to.

Bottom line: you should use `HTMLElement

**Comment by damercier** [comment]
Thanks @sjrd for the quick reply and the clarification.
