### ISSUE TITLE
TableHeaderCell is missing

### ISSUE THREAD

**Issue by mathieuleclaire** [scala-js/scala-js-dom#406]
Hi,
I ugpraded my code with scala-js-dom 1.0.0 and I get (only) one error with the tag ```th```: 

```scala
Symbol 'type org.scalajs.dom.html.TableHeaderCell' is missing from the classpath.
[error] This symbol is required by 'lazy value scalatags.jsdom.Tags.th'.
```
Any idea ?
Mathieu

**Comment by ritschwumm** [comment]
(HTML)TableHeaderCell, being a non-standard type, was deprecated in 0.9.8 (#360) and removed 1.0.0.  i think you should use (HTML)TableCellElement now.

**Comment by mathieuleclaire** [comment]
OK, thanks. Actually, the error comes from scalatags: https://github.com/lihaoyi/scalatags/blob/master/scalatags/js/src/scalatags/jsdom/Tags.scala#L82. I'll do a PR.
Thanks
