### ISSUE TITLE
URLSearchParams is missing from dom.window

### ISSUE THREAD

**Issue by rhz** [scala-js/scala-js-dom#407]
There is no facade for [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) that I can find.

**Comment by raquo** [comment]
It's here: https://github.com/scala-js/scala-js-dom/blob/0ede725b32637993da313be339a28d2756d9f921/src/main/scala/org/scalajs/dom/experimental/URL.scala#L106

JS class facades are registered on the global scope by means of `@JSGlobal` annotation, not by being physically located inside `dom.window`.

**Comment by rhz** [comment]
I see. Thanks! `:)`
