### ISSUE TITLE
Support Web Animation API

### ISSUE THREAD

**Issue by modoodalvi** [scala-js/scala-js-dom#413]
Although in [draft status](https://www.w3.org/TR/web-animations-1/), the upcoming [web animation API](https://developer.mozilla.org/de/docs/Web/API/Web_Animations_API) is already partially supported in the [most browsers](https://caniuse.com/#feat=web-animation). 

- Extend `org.scalajs.dom.raw.Element` and add a `animate` method
- Create the new `Animation` object

**Comment by armanbilge** [comment]
@modoodalvi sounds like something we can offer as an experimental API in v2, would you mind making a PR? :)

**Comment by modoodalvi** [comment]
No update
