### ISSUE TITLE
Publish a Dotty compatible version

### ISSUE THREAD

**Issue by davesmith00000** [scala-js/scala-js-dom#422]
I've started to try and migrate my project to Dotty to find out how much is possible, and scala-js-dom doesn't appear to have a dotty compatible release yet - if I'm not mistaken?

**Comment by sjrd** [comment]
Dotty can use the 2.13 version of libraries with `withDottyCompat`. Please use that to depend on the published version of scalajs-dom for 2.13. I have no plans to release a dotty-specific version at the moment.

**Comment by davesmith00000** [comment]
Ah ha! Thank you, I'll look into that.
