### ISSUE TITLE
Missing Node.isConnected

### ISSUE THREAD

**Issue by AugustNagro** [scala-js/scala-js-dom#443]
https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected

https://caniuse.com/mdn-api_node_isconnected

I can make a PR but it looks like there's many already waiting?

Maybe auto-generating via IDL would be helpful here.

**Comment by armanbilge** [comment]
@AugustNagro yes, please make a PR! Apologies for the backlog here, we'll be caught up soon, see this post for more details :)

https://users.scala-lang.org/t/scala-js-dom-to-become-more-active-2-x-coming-soon/
