### ISSUE TITLE
Missing Element.remove

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/scala-js-dom#447]
It seems DOM `Element` (in org.scalajs.dom.raw) misses the [remove](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) method.

It can be replaced by `e.parentNode.removeChild(e)`, but I think there is probably no reason not to add it.

**Comment by strelec** [comment]
Many more elementary DOM operations are missing (all of them very well supported in the browsers):

```
	@js.native
	trait ElementExt extends HTMLElement {
		def remove(): Unit = js.native
		def before(nodes: Node*): Unit = js.native
		def after(nodes: Node*): Unit = js.native

		def replaceChildren(nodes: Node*): Unit = js.native
		def prepend(nodes: Node*): Unit = js.native
		def append(nodes: Node*): Unit = js.native
	}
```

**Comment by armanbilge** [comment]
@strelec would you mind opening a PR with those additions please? Would be much much appreciated!
