### ISSUE TITLE
querySelectorAll should return Elements

### ISSUE THREAD

**Issue by theqp** [scala-js/scala-js-dom#455]
1. It's inconsistent with `querySelector` which returns `Element`
2. It's inconsistent with the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll)
> A non-live NodeList containing one **Element** object for each element that matches at least one of the specified selectors or an empty NodeList in case of no matches.

**Comment by raquo** [comment]
`querySelectorAll` returns a NodeList of Element-s:

    def querySelectorAll(selectors: String): NodeList = js.native

This matches what the MDN page that you quoted says that the JavaScript method returns.

I'm not sure what you mean by "inconsistent with `querySelector`", but scala-js-dom doesn't have a choice here. This interface follows the design of the underlying Javascript methods. Javascript `querySelectorAll` method returns a NodeList, and that's what scala-js-dom has to return as well for that method definition.

**Comment by theqp** [comment]
@raquo a `NodeList` is defined like this:
`class NodeList extends DOMList[Node]`
The MDN documentations states `querySelector` returns `Element`s, not `Node`s thus I think it should return `DOMList[Element]`

**Comment by raquo** [comment]
Ah, I see what you mean now.

I guess one way to encode it would be `class NodeList[N <: Node] extends DOMList[N]`.

**Comment by theqp** [comment]
@raquo 
We already have an eqvivalent
```scala
trait NodeListOf[TNode <: Node] extends DOMList[TNode]
```

**Comment by armanbilge** [comment]
@theqp or @raquo  would you mind making a PR for this? Would be much appreciated! :)
