### ISSUE TITLE
Release keys

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#462]
@sjrd We currently don't have the ability to perform releases and not only do we need to perform releases, I also want to automate it. Can you please share the keys? You've got my email

**Comment by sjrd** [comment]
It's the middle of the night here, but later today I'll setup the keys directly in the GitHub project Secrets, as explained here:
https://github.com/olafurpg/sbt-ci-release#secrets
If that's OK? That's what we did for scalajs-bundler.

Or do you have something else in mind to automate the release?

**Comment by japgolly** [comment]
No that's perfect, thanks @sjrd ! And no rush.

**Comment by sjrd** [comment]
All right, the Secrets should be correctly set up.
