### ISSUE TITLE
Split huge files into smaller units

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#476]
Atm we have huge files like `lib.scala` with tons of stuff in them. It would be nice to split this into a more traditional structure.

**Comment by armanbilge** [comment]
@japgolly Do you still want to do this?

**Comment by japgolly** [comment]
@armanbilge Oh no way lol. I absolutely do not want to do this but I was resolved to because it'll be valuable and make future maintenance easier. If you want to do though, feel free! I would be overjoyed lol

**Comment by armanbilge** [comment]
Lol! @sjrd also strongly recommended against in https://github.com/scala-js/scala-js-dom/issues/545#issuecomment-912187479. I think we should consider closing.

**Comment by japgolly** [comment]
My understanding of that comment is that he was against doing both changes at the same time. `git blame` isn't a compelling reason to me anyway for not improving the codebase. We should do the best we can by git but the value of the codebase far outweights the value of git, especially on a project like this where it's 99% facades. Plus do keep in mind that `git blame` is already useless due to reformatting. If we really want to know the history, `git blame` isn't the best way and it can still be achieved via git.

**Comment by armanbilge** [comment]
Ah, makes sense now. Ok, well I'll mark this help-wanted since basically anyone can do it.

**Comment by sjrd** [comment]
> My understanding of that comment is that he was against doing both changes at the same time.

That's indeed what I was saying.

**Comment by japgolly** [comment]
My understanding is that he was against doing both changes at the same
time. `git blame` isn't compelling cos we're moving everything around and
have reformatted it anyway.

**Comment by japgolly** [comment]
Automation coming to save the day................. :eyes:

**Comment by japgolly** [comment]
Hey @armanbilge just a an FYI, this is like 85% done but something came up, I got interrupted and it looks like I wont online for 4 days or so. Not even for reviewing your PRs unfortunately. Do with that info whatever you think is best, I'll be back next week, and sorry for any inconvenience :)

**Comment by armanbilge** [comment]
No worries, have a nice long weekend I hope!

**Comment by japgolly** [comment]
> looks like I wont online for 4 days or so

Ah yeah, sorry but I've had a bit of a medical emergency that blew out way beyond 4 days. It's going to take quite a while to resolve but slowly, slowly I'll starting coming back bit by bit. Sorry about the inconvenience and feel free to maintain away without my involvement. Don't want to hold anyone back.

**Comment by armanbilge** [comment]
Don't worry at all, wishing a healthy recovery so please take all the time you need. Thanks for clearing the PR queue, I'll keep chugging away.

**Comment by japgolly** [comment]
Thanks @armanbilge !
