### ISSUE TITLE
GH Action Release fails

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#477]
@armanbilge Release failed on the `series/v1.x` branch, seemingly cos of SJS 0.6.x. I know it's just SNAPSHOT release but if it doesn't work, pushing a v1.2.0 tag wont work either sadly.

https://github.com/scala-js/scala-js-dom/actions/runs/1125835306

**Comment by armanbilge** [comment]
Shoot, this was working before. On it.

**Comment by armanbilge** [comment]
Fixed 😅
