### ISSUE TITLE
Change auto-formatting settings

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#479]
Once our PR queue is cleared, on the 2.x branch lets:

* [x] Add import normalisation and sorting to auto-formatting (I use it everywhere and it's GLORIOUS)
* [x] I wouldn't mind increasing the column width from 79 to 120
* [x] Format ScalaDoc in a more concise way - it takes up so much vertical space atm
* [ ] Force use of `override`
* [ ] sort members
* [ ] More?

**Comment by armanbilge** [comment]
Yes PLEASE! Formatting for `build.sbt` as well.

**Comment by japgolly** [comment]
I think we're good enough. I don't see a rule for the other features (and I'm not gonna write myself this time) so I'll just close this hey
