### ISSUE TITLE
API report - sort members by name rather than `<decltype> <name>`

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#482]
Comparing against mdn is pretty hard when all the `def`s come before all the `val` followed by all the `var`s

**Comment by armanbilge** [comment]
I can give this a shot! It will be a disruptive change though.

**Comment by japgolly** [comment]
Yeah absolutely! If you haven't got it working after like... say an hour, can I give you a bit of guidance? (I'm hoping to put it to good use today)

**Comment by armanbilge** [comment]
I mean, you should just do it then :) the philosophy is helping not blocking!

**Comment by armanbilge** [comment]
I gave it a shot in #483.

**Comment by armanbilge** [comment]
Fixed in #484
