### ISSUE TITLE
Support Clipboard API

### ISSUE THREAD

**Issue by strelec** [scala-js/scala-js-dom#490]
There appears to be two API, synchronous and the more modern, Promise-based one. We shall support the latter. Can be done post-2.0, once this api is more than 95% supported.

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

https://caniuse.com/async-clipboard

**Comment by armanbilge** [comment]
Apparently we've already had this, for a while.

https://github.com/scala-js/scala-js-dom/blob/dde2aba0a9aa7ee85a7242e875f12bc54509ffc9/dom/src/main/scala/org/scalajs/dom/Clipboard.scala

**Comment by Quafadas** [comment]
For posterity.

```
dom.window.navigator.clipboard.writeText("hi")
```
