### ISSUE TITLE
`prePR` doesn't generate reports on `master`

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#524]
Gotta add `(root / Compile / scalafix).toTask("")` back in

**Comment by armanbilge** [comment]
Oops!

**Comment by japgolly** [comment]
Hehe. I think you disabled it cos of Scala 3. Gonna have to find a temporary workaround I think...

**Comment by armanbilge** [comment]
We can just add a scala version check I think.

**Comment by armanbilge** [comment]
Wait, maybe I did something stupid in #512 and deleted every line with "delete if scala 2.10" when what I should have done is delete the comment and otherwise leave alone.

**Comment by japgolly** [comment]
Yeah I was just having a look at https://github.com/scalacenter/scalafix/issues/1316 and it seems Scalafix still doesn't support Scala 3. I could've sworn a read a few weeks ago that it does now.

*Edit:* now I'm seeing some PRs that indicate that it might be supported after all, looking in to it atm....

**Comment by armanbilge** [comment]
The sbt plugin supports scala 3 I think, but the core module was not published for scala3 which is why I snuck a `for3Use213` into the build.

**Comment by japgolly** [comment]
So is there a way to use it on Scala 3 builds? I'm a bit confused

**Comment by armanbilge** [comment]
I restored `(root / Compile / scalafix).toTask("")` and I'm just about to give it a try, we'll see

**Comment by armanbilge** [comment]
@japgolly this is what spits out:
```
To use Scalafix on Scala 3 projects, you must unset `scalafixBinaryScalaVersion`. Rules such as ExplicitResultTypes requiring the project version to match the Scalafix version are unsupported for the moment.
```

**Comment by japgolly** [comment]
Problems:
* `RemoveUnused` can't be used with Scala 3 because there isn't a `-Wunused` flag in Scala 3 yet
* Setting `scalafixBinaryScalaVersion` to `2.13` and hardcoding `scalaVersion := "2.13.4"` in the `scalafixRules` settings works **but** unfortunately no semantic information is available so `GenerateApiReports` crashes

We're just gonna have to disable scalafix all together for Scala 3 in a way that
* `prePR` works
* we don't have source-patching hacks like we did for Scala 2.10

**Comment by armanbilge** [comment]
I think that's doable, I'm on it in #525.
