### ISSUE TITLE
Can we get rid of `MDN` in all the ScalaDoc?

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js-dom#553]
It's annoying and useless IMO. Do we really need it? A link to the actual mdn page would be great, but just stating `MDN` seems pretty useless to me.

If it's for licencing issues,

1. we could just make a licencing statement upfront, once, about comments and MDN.
2. descriptions of API aren't copyrightable anyway. Even API itself isn't copyright-able according to Google vs Oracle.

**Comment by armanbilge** [comment]
See also: https://developer.mozilla.org/en-US/docs/MDN/About#copyrights_and_licenses

This is fair issue, trying to reconcile what to do.

> descriptions of API aren't copyrightable anyway.

Do you have a source for this? IMO (IANAL) I would think that documentation _may_ be copyright-able even if API isn't. Otherwise, it starts to get a bit fuzzy, where do you draw the line between e.g. copyrightable book/tutorial about how to use an API vs the documentation?

**Comment by armanbilge** [comment]
See also the current LICENSE: https://github.com/scala-js/scala-js-dom/blob/master/LICENSE

**Comment by japgolly** [comment]
From https://developer.mozilla.org/en-US/docs/MDN/About#copyrights_and_licenses

> Please attribute "Mozilla Contributors" and include a hyperlink (online) or URL (in print) to the specific wiki page for the content being sourced

Whoops, we're already failing that pretty badly. Restoring it in each specific comment isn't feasible without automation (which let's be honest, neither of us are going to spend time on).

But we could do is declare upfront in one top-level place our usage of MDN, and then provide a link to the entire MDN. There are no rules about where exactly to place the attribution, just that we do provide attribution to MDN.

**Comment by armanbilge** [comment]
> But we could do is declare upfront in one top-level place our usage of MDN

Yep, that's done in scala-js-dom `LICENSE` I linked above.

> Documentation marked "MDN" is thanks to Mozilla Contributors

Ok, so maybe here's how we get out of this: instead of indicating MDN in our scaladocs, in our license we just say all documentation is copyright MDN unless noted otherwise. So, then we'll have to mark our own docs "SJS" or something 😝

**Comment by japgolly** [comment]
(1) Yeah exactly, and I think that would be better than `MDN` on 99.9% of all ScalaDoc.

(2) That being said I also think it would be fine to just state upfront "hey most comes from MDN, here's the link" and leave it for anyone interested (which I can't imagine ever happening) to see themselves as it's easily derivable.

But if you don't like (2), I'm happy with (1)

**Comment by armanbilge** [comment]
I'll PR this!
