### ISSUE TITLE
Should `opaque type`s subtype `String`?

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js-dom#594]
Came up in https://github.com/scala-js/scala-js-dom/pull/592#discussion_r726056999 but we deferred the decision.

**Comment by japgolly** [comment]
We can close this now, right @armanbilge ?

**Comment by japgolly** [comment]
Oh right. Went and read the comment. Yeah sounds good to me, is there any reason not subtype `String`?

**Comment by japgolly** [comment]
Actually it should only take a second. How about I regex up a PR and then cut an RC right after?
