### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js-dom#595]
We're right at the finish line! The outstanding PRs are:
- #588: reviewed by @japgolly, needs a final review
- #592: reviewed by @sjrd, based on #588
- #593: basically ready, let's get this one in as well

The only other issues in the [2.0.0 milestone](https://github.com/scala-js/scala-js-dom/milestone/2) are internal and don't have binary or source compatibility implications, so I don't think we should block on those.

Is there anything else?

I don't mean to be impatient or pushy, there's no real rush of course. But speaking personally I'll be very happy to have this weight off my shoulders and see all of our efforts come to fruition. And importantly start the process of propagating this change through the ecosystem.

**Comment by sjrd** [comment]
FYI, I will be on vacation the week of October 25. I don't think you'll need me for the release at all, but just in case. ;)

**Comment by armanbilge** [comment]
Well I did goof it up once before 😳 thanks for letting me know. In theory we can release anytime this week (all the aforementioned PRs are ready), I am hopeful David will chime in with his blessings/objections :)

**Comment by japgolly** [comment]
Hello. Sounds great, let's get this release out. My only contribution to the plan is that I think it'd be a good idea to do an RC first. One reason is that the new release process is still new, another reason is that I'd love to try it in a big app, make sure everything works as expected and all tests pass, so that if there are any mistakes we've made, hopefully we catch them in time before locking ourselves into bincompat for the entire 2.x series. Actually it might be a good idea to let the community do the same.

**Comment by armanbilge** [comment]
FWIW, what I'm most concerned about re binary compatibility, is making sure we loudly communicate that downstreams should remove the `for3use213` from their build configs. Because it is far too easy to merge a Scala Steward update to SJS-dom v2 without paying attention to this.

**Comment by japgolly** [comment]
Yeah very good point! Maybe a big bold instruction at the top of the release notes?

> Thanks for chiming in! Hope all is well

Thank you! Unfortunately it's just bad news after bad news. Funny thing is that I have unrelated appt next month that about something that could be cancer which, I think at this point I'd just laugh and say ggs. I'll probably be fine eventually though. Unfortunately for my OSS contributions I might be a bit randomly flakey for a while. I am sorry about that but not much I can do. Looks like you've been doing awesome work so as both a co-contributor and as an end-user, thank you!!

**Comment by armanbilge** [comment]
I'm am so sorry to hear that 😢 I certainly don't want to pile on, and hope that I haven't by pushing for this release. Just let me know.

**Comment by japgolly** [comment]
Oh my bad, no, no, not at all. Nothing like that :) When I have a bit of capacity I like to pop it and do what I again. No pressure :)

**Comment by japgolly** [comment]
> Should we cut an RC?

Yeah let's do it! In fact, I'll do it now...

**Comment by armanbilge** [comment]
Nice! I am currently looking through SJS-dom dependencies to try and figure out what important projects to help along with a PR.

https://mvnrepository.com/artifact/org.scala-js/scalajs-dom/usages

**Comment by armanbilge** [comment]
Nice, looks like scalajs-react merged in the RC 🎉 Can we promote to 2.0.0 final?

**Comment by japgolly** [comment]
> Nice, looks like scalajs-react merged in the RC :tada: Can we promote to 2.0.0 final?

Nah, scalajs-react isn't much of a test,  I wanna upgrade this in a big app before we lock in bincompat

**Comment by japgolly** [comment]
#615 is a blocker, else we'd be locked into bincompat of `ReadyState` being only applicable to `MediaSource`.

**Comment by japgolly** [comment]
FYI: Added a little migration helper script that I used to the release notes (same as I do for scalajs-react releases those who follow that). It obviously won't do everything but it's a nice ~80% reward for ~20% effort.

**Comment by armanbilge** [comment]
Cool! You added this where? 😀

**Comment by japgolly** [comment]
The draft release page for 2.0.0

**Comment by japgolly** [comment]
Alrighty, those two PRs are my last. After they're merged, we're good to  from my side. :rocket: :rocket: :rocket:

**Comment by armanbilge** [comment]
We're on central!
https://repo1.maven.org/maven2/org/scala-js/scalajs-dom_sjs1_2.13/2.0.0/
