### ISSUE TITLE
MouseEvent.buttons doesn't work in Chrome

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js-dom#60]
Maybe it's a Firefox only thing? Since it's defined [here](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent). If it is, we should probably move it out of the default namespace

**Comment by mseddon** [comment]
It's currently in the working draft, so perhaps Chrome hasn't adopted it yet http://www.w3.org/TR/DOM-Level-3-Events/#widl-MouseEvent-buttons

**Comment by mseddon** [comment]
https://code.google.com/p/chromium/issues/detail?id=276941 this issue should be fixed.  It appears to be working in Chrome Version 43.0.2357.125 (64-bit) under linux.

**Comment by mseddon** [comment]
@sjrd this is confirmed working under Linux and Win32 in Chrome 43, and MDN now lists this fact https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons, I believe this issue can be closed.
