### ISSUE TITLE
Create facade for `Image`

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js-dom#621]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

ScalablyTyped _thought_ we had this, so we may as well add it :)

**Comment by zetashift** [comment]
So far I've got this:

```scala
/** Image creates a new HTMLImageElement instance. It is functionally equivalent to document.createElement('img').
  *
  * @param width
  *   The width of the image (i.e., the value for the width attribute).
  * @param height
  *   The height of the image (i.e., the value for the height attribute).
  */
class Image(width: Int, height: Int) extends HTMLImageElement
```
`
However in my exploration I see that the `HTMLImageElement` is missing some properties, for example:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading 

https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset

Want me to add these as well in the same PR?

**Comment by armanbilge** [comment]
Sure, if you're up for it! :)
