### ISSUE TITLE
Fetch request body as ReadableStream

### ISSUE THREAD

**Issue by ptrdom** [scala-js/scala-js-dom#622]
According to the specs, Fetch should be able to handle `ReadableStream` as request body. Implementing this would likely result in some changes to `ReadableStream` and `ReadableStreamController` facades - `ReadableStream` needs a constructor that implements the `underlyingSource`, which allows interaction with `ReadableStreamController`, and `ReadableStreamController` should not have its own constructor, as it is constructed by `ReadableStream` during its construction.

If implementing this would be approved, I could give it a shot.

References:
- https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters
- https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/ReadableStream
- https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultController

**Comment by armanbilge** [comment]
Thanks for this! 👍 to these changes, the goal is to match the spec so a contribution for this would be _very_ welcome 😁 

_However_, just so you are aware ... I recently implemented a `Fetch`-based client as well in [`http4s-dom`](https://github.com/http4s/http4s-dom) and tried using a `ReadableStream` in the request body, but was dissapointed to learn that many browsers have not implemented this feature for requests. See:

https://caniuse.com/mdn-api_request_request_readablestream_request_body

**Comment by ptrdom** [comment]
I have just realized that also, while playing around with possible new version of the facade 😞. I guess it still makes sense to have the upgraded facade in case someone might find some use for natively available streaming implementation and to prepare for eventual browser support for `ReadableStream` in `Fetch` request body.

I will start working on the PR then.

**Comment by armanbilge** [comment]
Thanks! The enhancements for `ReadableStream` in general are a good idea, and even though browsers have not implemented it, there are other environments that have, such as Cloudflare Workers (serverless):
https://developers.cloudflare.com/workers/runtime-apis/request#requestinit

**Comment by armanbilge** [comment]
Good news, it seems that Chrome will finally be supporting this:
https://developer.chrome.com/articles/fetch-streaming-requests/

Hopefully other browsers will follow suit.
