### ISSUE TITLE
Add `URLSearchParams` to `BodyInit` for fetch

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js-dom#634]
https://github.com/scala-js/scala-js-dom/blob/e7254c8a5729ee6a86b83111587522efa0955c31/dom/src/main/scala/org/scalajs/dom/package.scala#L35

**Comment by zetashift** [comment]
Shouldn't the scaladoc comment for BodyInit point to https://fetch.spec.whatwg.org/#bodyinit-unions ? At the very least the current link links to the ToC of the spec hehe.

Also is this issue really as easy as just adding `URLSearchParams` to the union?

**Comment by armanbilge** [comment]
Thanks, that seems better :)

> Also is this issue really as easy as just adding `URLSearchParams` to the union?

Famous last words 😝 it _should_ be, but I haven't checked if `URLSearchParams` exists at least 😂

**Comment by zetashift** [comment]
Yea if it didn't exist I'd be worried,
but:
https://github.com/scala-js/scala-js-dom/blob/51a807cc04ea134ece030d6d4005a8ce30c1de99/dom/src/main/scala/org/scalajs/dom/URLSearchParams.scala
