### ISSUE TITLE
Facade for `setImmediate` and `clearImmediate`

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js-dom#652]
Since we are now facading APIs regardless of their experimental status or overall adoption, would it make sense for us to facade `setImmediate` and `clearImmediate`? It is [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) after all.

Although by itself this facade is useless in virtually all browsers, when paired with an npm dependency to the [setimmediate polyfill](https://www.npmjs.com/package/setimmediate) it becomes much more useful. Edit: seems also available as a [webjar](https://www.webjars.org/listfiles/org.webjars.npm/setimmediate/1.0.5).

@japgolly wdyt? This would address your use-case in https://github.com/scala-js/scala-js-macrotask-executor/pull/37.

**Comment by sjrd** [comment]
> Since we are now facading APIs regardless of their experimental status or overall adoption

Adoption, yes. Status, not so much. We should stick to APIs that are standardized in the DOM. Or at the very least, *on track* to become standard in the DOM.

AFAIK, `setImmediate` has been indefinitely rejected as a proposal for DOM, and therefore it should not be in scalajs-dom, IMO.

**Comment by armanbilge** [comment]
> Or at the very least, _on track_ to become standard in the DOM.

Thanks, that's an important distinction. Indeed, MDN says at least twice that `setImmediate` is not on this track.

> This feature is non-standard and is not on a standards track.

> This method is not expected to become standard,

I assume that `setImmediate` was on a standards track on some point, before being rejected, so it's interesting to think about if the facade had been introduced at that point; in that case, I suppose we should have deprecated it?

As I wrote the above, I thought to check: indeed, `setImmediate` _was_ facaded in scala-js-dom once upon a time ago and deprecated as part of https://github.com/scala-js/scala-js-dom/pull/255 and subsequently removed (although I didn't track down that commit).

Let's give @japgolly a chance to weigh in.
