### ISSUE TITLE
bogus Extensions.scala in out.map.js

### ISSUE THREAD

**Issue by tballard** [scala-js/scala-js-dom#688]
In my out.map.js sources list there is the following entry:

"file:///home/runner/work/scala-js-dom/scala-js-dom/src/main/scala/org/scalajs/dom/ext/Extensions.scala"

Well, there is no such file on my box and I can't actually even write in that directory. I was chasing a bug when I found an error about it somewhere. It turns it was not actually the cause of the bug so I'm not too concerned, but I bet one of your developers has/had that file on his machine and somhow the buid kept a reference to it.

**Comment by armanbilge** [comment]
Thanks for the report. I assume that you are using scala-js-dom 1.x? It seems to be referencing this file here:
https://github.com/scala-js/scala-js-dom/blob/series/1.x/src/main/scala/org/scalajs/dom/ext/Extensions.scala

`/home/runner/work/scala-js-dom/...` is actually the path used by GitHub CI machines when publishing scala-js-dom artifacts to Sonatype/Maven. So, it seems like our sourcemaps may not be configured correctly.
