### ISSUE TITLE
Missing basic DOM operation: Element.replaceWith

### ISSUE THREAD

**Issue by strelec** [scala-js/scala-js-dom#692]
Pretty much supported in all browsers: https://caniuse.com/mdn-api_element_replacewith
DOM Standard: https://dom.spec.whatwg.org/#interface-childnode
MDN: https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceWith

**Comment by armanbilge** [comment]
Thanks, PRs happily accepted! :)
