### ISSUE TITLE
Autogenerating using IDL files?

### ISSUE THREAD

**Issue by peter-jerry-ye** [scala-js/scala-js-dom#716]
Hello,

I see that the DOM is added bit by bit, and it seems that it lacks much interface (the InputEvent is only recently added for example). 
I myself has helped with some interface (for custom element), but it seems repetitive work, and it requires careful implementation to avoid typos etc.

So might I ask if there's any possibility that it gets generated from the webkit idl files like what is done in [ghcjs](https://github.com/ghcjs/ghcjs-dom)?

Thank you.

**Comment by armanbilge** [comment]
Thanks for your contributions to the project! Discussion of code generation strategies is in https://github.com/scala-js/scala-js-dom/discussions/487 and your ideas would be very welcome :)

**Comment by peter-jerry-ye** [comment]
Oh, sorry that I've missed the discussion functionality of Github. I shall close this issue then.
