### ISSUE TITLE
Add code member to KeyboardEvent

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/scala-js-dom#726]
[KeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) should contain [code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) member. This is useful when one wants to identify keys on prominent locations like Backquote even with international layouts, which do not have "`" printable representation for that key.

**Comment by armanbilge** [comment]
Thanks! A PR would be welcome to add this :)
