### ISSUE TITLE
`Clipboard#{read,write}` are wrong

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js-dom#730]
According to the MDN docs, `read` and `write` should be in terms of a `js.Array[ClipboardItem]`. But that's not what a `DataTransfer` is ...

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard

https://github.com/scala-js/scala-js-dom/blob/51a807cc04ea134ece030d6d4005a8ce30c1de99/dom/src/main/scala/org/scalajs/dom/Clipboard.scala#L28

https://github.com/scala-js/scala-js-dom/blob/51a807cc04ea134ece030d6d4005a8ce30c1de99/dom/src/main/scala/org/scalajs/dom/Clipboard.scala#L41

**Comment by zetashift** [comment]
I can pick this up if you like!

**Comment by armanbilge** [comment]
@zetashift yes please! 😃 I have a renewed interest in all these APIs because of my new fs2-dom pet project 😋

**Comment by zetashift** [comment]
From https://w3c.github.io/clipboard-apis/#dom-clipboard-write

I can't _exactly_ figure out what kind of `promise` should return?

Currently have this:
```scala
  def write(data: DataTransfer): js.Promise[ClipboardItem] = js.native
```

**Comment by armanbilge** [comment]
@zetashift I think it should be this
```scala
  def write(data: ClipboardItems): js.Promise[Unit] = js.native
```

`undefined` is `()` aka `Unit` in Scala.js
