### ISSUE TITLE
Refresh `DataTransfer` API

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js-dom#738]
I think there are some changes. Also it can use the new `FrozenArray` type.

https://github.com/scala-js/scala-js-dom/blob/714813e31cf5838d9844141f7bc1b90275f79fa3/dom/src/main/scala/org/scalajs/dom/DataTransfer.scala

https://html.spec.whatwg.org/multipage/dnd.html#datatransfer

**Comment by zetashift** [comment]
I have a question concerning `effectAllowed` and `dropEffect`. They return enums form the spec

> The dropEffect attribute controls the drag-and-drop feedback that the user is given during a drag-and-drop operation. When the [DataTransfer](https://html.spec.whatwg.org/multipage/dnd.html#datatransfer) object is created, the [dropEffect](https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-dropeffect) attribute is set to a string value. On getting, it must return its current value. On setting, if the new value is one of "none", "copy", "link", or "move", then the attribute's current value must be set to the new value. Other values must be ignored.

> The effectAllowed attribute is used in the drag-and-drop processing model to initialize the [dropEffect](https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-dropeffect) attribute during the [dragenter](https://html.spec.whatwg.org/multipage/dnd.html#event-dnd-dragenter) and [dragover](https://html.spec.whatwg.org/multipage/dnd.html#event-dnd-dragover) events. When the [DataTransfer](https://html.spec.whatwg.org/multipage/dnd.html#datatransfer) object is created, the [effectAllowed](https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-effectallowed) attribute is set to a string value. On getting, it must return its current value. On setting, if [drag data store](https://html.spec.whatwg.org/multipage/dnd.html#drag-data-store)'s [mode](https://html.spec.whatwg.org/multipage/dnd.html#drag-data-store-mode) is the [read/write mode](https://html.spec.whatwg.org/multipage/dnd.html#concept-dnd-rw) and the new value is one of "none", "copy", "copyLink", "copyMove", "link", "linkMove", "move", "all", or "uninitialized", then the attribute's current value must be set to the new value. Otherwise it must be left unchanged.

But how do I name these things lol, `EffectAllowedTypes` and `DropEffectTypes`? or `Kinds` instead of types?

**Comment by armanbilge** [comment]
Hmmm 😂  I see TypeScript is no help here.

https://github.com/microsoft/TypeScript/blob/7d1cc88a8cbdf8aa847a7f2a7d4bfeb89c8dde15/lib/lib.dom.d.ts#L4302-L4318

erm ... IDK. `DropEffectOperation` ? but `EffectAllowedOperation` seems weird.

**Comment by zetashift** [comment]
`DropEffectValue` and `EffectAllowedValue`?

I'm also okay `DropEffect` and `EffectAllowed`!

**Comment by armanbilge** [comment]
/shrug if you don't mind open the PR with anything and then let me bikeshed it for 6 months 😛
