### ISSUE TITLE
LockOptions doesn't use val for fields, making overriding not possible

### ISSUE THREAD

**Issue by jypma** [scala-js/scala-js-dom#833]
Most traits in `scala-js-dom` extending `js.Object` use `val` for their members, so they can be overridden selectively. See e.g. [`IDBCreateObjectStoreOptions`](https://github.com/scala-js/scala-js-dom/blob/main/dom/src/main/scala/org/scalajs/dom/IDBCreateObjectStoreOptions.scala). This pattern is also recommended by the [scalajs documentation](https://www.scala-js.org/doc/interoperability/types.html):

```scala
trait MyObject extends js.Object {
  val foo: Int = js.native
  val bar: String = js.native
}
```

This allows a user to selectively override only some fields, e.g.

```scala
new MyObject {
  override def foo = 5
}
```

However, [`dom.LockOptions`](https://github.com/scala-js/scala-js-dom/blob/main/dom/src/main/scala/org/scalajs/dom/LockOptions.scala) currently uses `var`. This means that this object needs to be instantiated as `new LockOptions {}`, and then the mutable fields can be changed.

This makes `LockOptions` inconsistent with the other objects. However, changing it to `val` would be a binary incompatible change, so I'm not sure of the proper way forward.

**Comment by sjrd** [comment]
The `var` idiom is the new, better one. We should update the Scala.js docs if they still appear to recommend the `val` idiom by default.

(abstract `val` is good for non-optional members; optional ones are better served with a `var ... = js.undefined`)

**Comment by jypma** [comment]
Ah, thanks a lot for clarifying! I guess it does make sense, JS objects are mutable either way. I suppose that inverts my original question ;-)
